#!/usr/sbin/nft -f

# Limpa todas as regras anteriores antes de aplicar as novas
flush ruleset

table inet filter {
	#-----------------------------------------------
	# TRAFEGO DE ENTRADA (Quem tenta acessar o seu debian)
	#-----------------------------------------------
	chain input {
		type filter hook input priority filter; policy drop;

		# 1. Permite comunicacao interna do próprio sistema (Loopback)
		iif "lo" accept

		# 2. Mantem conexoes ja abertas e autorizadas (Evita quedas)
		ct state established,related accept

		#3. Permite Ping (ICMP) vindo apenas da sua rede local
		ip saddr 192.168.1.0/24 icmp type echo-request accept

		#4. Permite SSH (Porta 22) para todo DHCP da sua rede local
		ip saddr 192.168.1.0/24 tcp dport 22 accept

		#5. Permite Servidor Web (Porta 80) na sua rede local
		ip saddr 192.168.1.0/24 tcp dport 80 accept

		#6.Permite que rede local consulte o Dnsmasq
		ip saddr 192.168.1.0/24 udp dport 53 accept
		ip saddr 192.168.1.0/24 tcp dport 53 accept

		#7.Permite o samba apenas para a rede local
		ip saddr 192.168.1.0/24 udp dport { 137, 138 } accept
		ip saddr 192.168.1.0/24 tcp dport { 139, 445 } accept

		#LOG
		limit rate 10/minute burst 5 packets log prefix "NFT_DROP: "
	}
	#-----------------------------------------------------------
	# TRAFEGO DE ENCAMINHAMENTO (Se o Debian fosse um roteador)
	#-----------------------------------------------------------
	chain forward {
		type filter hook forward priority filter; policy drop;
	}
	#-----------------------------------------------------------------------------
	#TRAFEGO DE ENCAMINHAMENTO (O que o seu debian pode acessar na rede/internet)
	#-----------------------------------------------------------------------------
	chain output {
		type filter hook output priority filter;
		policy accept;

		#1. permite comunicacao interna do proprio sistema (Loopback)
		#oif "lo" accept

		#2. Permite responder a acessos vindos do seu Windows
		#ct state established,related accept

		#3.Permite consultas DNS (Porta 53) para o debian resolver nomes de sites
		#udp dport 53 accept
		#tcp dport 53 accept

		#4. Permite acessar a internet para baixar atualizacoes (http/https)
		#tcp dport { 80, 443 } accept
	}
}
